FROM python:3.9-bullseye

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./ /code/

EXPOSE 8501

CMD ["python", "-m", "streamlit", "run", "main.py", "--server.port", "8501"]
